version: '3'
services:
  api:
    build:
      context: ./NodeAPI
      dockerfile: ./Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - "./NodeAPI:/app"
    env_file:
      - ./NodeAPI/.env
  renderer:
    build:
      context:  ./IsomorphicReactApp
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - "./IsomorphicReactApp:/app"
    env_file:
      - ./IsomorphicReactApp/.env
